// Code generated by MockGen. DO NOT EDIT.
// Source: middlewares.go
//
// Generated by this command:
//
//	mockgen -source=middlewares.go -destination=../mocks/middlewares.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/samandr77/microservices/payment/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// User mocks base method.
func (m *MockAuthService) User(ctx context.Context, token string) (entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User", ctx, token)
	ret0, _ := ret[0].(entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockAuthServiceMockRecorder) User(ctx, token any) *MockAuthServiceUserCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockAuthService)(nil).User), ctx, token)
	return &MockAuthServiceUserCall{Call: call}
}

// MockAuthServiceUserCall wrap *gomock.Call
type MockAuthServiceUserCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuthServiceUserCall) Return(arg0 entity.User, arg1 error) *MockAuthServiceUserCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuthServiceUserCall) Do(f func(context.Context, string) (entity.User, error)) *MockAuthServiceUserCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuthServiceUserCall) DoAndReturn(f func(context.Context, string) (entity.User, error)) *MockAuthServiceUserCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
