// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../mocks/service.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/gofrs/uuid/v5"
	decimal "github.com/shopspring/decimal"
	entity "github.com/samandr77/microservices/payment/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateTransaction mocks base method.
func (m *MockRepository) CreateTransaction(ctx context.Context, tx entity.Transaction) (entity.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", ctx, tx)
	ret0, _ := ret[0].(entity.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockRepositoryMockRecorder) CreateTransaction(ctx, tx any) *MockRepositoryCreateTransactionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockRepository)(nil).CreateTransaction), ctx, tx)
	return &MockRepositoryCreateTransactionCall{Call: call}
}

// MockRepositoryCreateTransactionCall wrap *gomock.Call
type MockRepositoryCreateTransactionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCreateTransactionCall) Return(arg0 entity.Transaction, arg1 error) *MockRepositoryCreateTransactionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCreateTransactionCall) Do(f func(context.Context, entity.Transaction) (entity.Transaction, error)) *MockRepositoryCreateTransactionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCreateTransactionCall) DoAndReturn(f func(context.Context, entity.Transaction) (entity.Transaction, error)) *MockRepositoryCreateTransactionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// NotPaidTransactions mocks base method.
func (m *MockRepository) NotPaidTransactions(ctx context.Context, paymentMethod entity.PaymentMethod) ([]entity.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotPaidTransactions", ctx, paymentMethod)
	ret0, _ := ret[0].([]entity.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NotPaidTransactions indicates an expected call of NotPaidTransactions.
func (mr *MockRepositoryMockRecorder) NotPaidTransactions(ctx, paymentMethod any) *MockRepositoryNotPaidTransactionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotPaidTransactions", reflect.TypeOf((*MockRepository)(nil).NotPaidTransactions), ctx, paymentMethod)
	return &MockRepositoryNotPaidTransactionsCall{Call: call}
}

// MockRepositoryNotPaidTransactionsCall wrap *gomock.Call
type MockRepositoryNotPaidTransactionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryNotPaidTransactionsCall) Return(arg0 []entity.Transaction, arg1 error) *MockRepositoryNotPaidTransactionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryNotPaidTransactionsCall) Do(f func(context.Context, entity.PaymentMethod) ([]entity.Transaction, error)) *MockRepositoryNotPaidTransactionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryNotPaidTransactionsCall) DoAndReturn(f func(context.Context, entity.PaymentMethod) ([]entity.Transaction, error)) *MockRepositoryNotPaidTransactionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveInvoiceURL mocks base method.
func (m *MockRepository) SaveInvoiceURL(ctx context.Context, billNumber int64, url string, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveInvoiceURL", ctx, billNumber, url, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveInvoiceURL indicates an expected call of SaveInvoiceURL.
func (mr *MockRepositoryMockRecorder) SaveInvoiceURL(ctx, billNumber, url, updatedAt any) *MockRepositorySaveInvoiceURLCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveInvoiceURL", reflect.TypeOf((*MockRepository)(nil).SaveInvoiceURL), ctx, billNumber, url, updatedAt)
	return &MockRepositorySaveInvoiceURLCall{Call: call}
}

// MockRepositorySaveInvoiceURLCall wrap *gomock.Call
type MockRepositorySaveInvoiceURLCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositorySaveInvoiceURLCall) Return(arg0 error) *MockRepositorySaveInvoiceURLCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositorySaveInvoiceURLCall) Do(f func(context.Context, int64, string, time.Time) error) *MockRepositorySaveInvoiceURLCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositorySaveInvoiceURLCall) DoAndReturn(f func(context.Context, int64, string, time.Time) error) *MockRepositorySaveInvoiceURLCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetStatus mocks base method.
func (m *MockRepository) SetStatus(ctx context.Context, prevStatus, status entity.TransactionStatus, createdAtFrom time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatus", ctx, prevStatus, status, createdAtFrom)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockRepositoryMockRecorder) SetStatus(ctx, prevStatus, status, createdAtFrom any) *MockRepositorySetStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockRepository)(nil).SetStatus), ctx, prevStatus, status, createdAtFrom)
	return &MockRepositorySetStatusCall{Call: call}
}

// MockRepositorySetStatusCall wrap *gomock.Call
type MockRepositorySetStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositorySetStatusCall) Return(arg0 error) *MockRepositorySetStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositorySetStatusCall) Do(f func(context.Context, entity.TransactionStatus, entity.TransactionStatus, time.Time) error) *MockRepositorySetStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositorySetStatusCall) DoAndReturn(f func(context.Context, entity.TransactionStatus, entity.TransactionStatus, time.Time) error) *MockRepositorySetStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Transaction mocks base method.
func (m *MockRepository) Transaction(ctx context.Context, id uuid.UUID) (entity.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, id)
	ret0, _ := ret[0].(entity.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Transaction indicates an expected call of Transaction.
func (mr *MockRepositoryMockRecorder) Transaction(ctx, id any) *MockRepositoryTransactionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockRepository)(nil).Transaction), ctx, id)
	return &MockRepositoryTransactionCall{Call: call}
}

// MockRepositoryTransactionCall wrap *gomock.Call
type MockRepositoryTransactionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryTransactionCall) Return(arg0 entity.Transaction, arg1 error) *MockRepositoryTransactionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryTransactionCall) Do(f func(context.Context, uuid.UUID) (entity.Transaction, error)) *MockRepositoryTransactionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryTransactionCall) DoAndReturn(f func(context.Context, uuid.UUID) (entity.Transaction, error)) *MockRepositoryTransactionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TransactionByGUID mocks base method.
func (m *MockRepository) TransactionByGUID(ctx context.Context, clientGUID uuid.UUID, number int64) (entity.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransactionByGUID", ctx, clientGUID, number)
	ret0, _ := ret[0].(entity.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransactionByGUID indicates an expected call of TransactionByGUID.
func (mr *MockRepositoryMockRecorder) TransactionByGUID(ctx, clientGUID, number any) *MockRepositoryTransactionByGUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransactionByGUID", reflect.TypeOf((*MockRepository)(nil).TransactionByGUID), ctx, clientGUID, number)
	return &MockRepositoryTransactionByGUIDCall{Call: call}
}

// MockRepositoryTransactionByGUIDCall wrap *gomock.Call
type MockRepositoryTransactionByGUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryTransactionByGUIDCall) Return(arg0 entity.Transaction, arg1 error) *MockRepositoryTransactionByGUIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryTransactionByGUIDCall) Do(f func(context.Context, uuid.UUID, int64) (entity.Transaction, error)) *MockRepositoryTransactionByGUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryTransactionByGUIDCall) DoAndReturn(f func(context.Context, uuid.UUID, int64) (entity.Transaction, error)) *MockRepositoryTransactionByGUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Transactions mocks base method.
func (m *MockRepository) Transactions(ctx context.Context, clientID uuid.UUID, filter entity.TransactionFilter) ([]entity.Transaction, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transactions", ctx, clientID, filter)
	ret0, _ := ret[0].([]entity.Transaction)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Transactions indicates an expected call of Transactions.
func (mr *MockRepositoryMockRecorder) Transactions(ctx, clientID, filter any) *MockRepositoryTransactionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transactions", reflect.TypeOf((*MockRepository)(nil).Transactions), ctx, clientID, filter)
	return &MockRepositoryTransactionsCall{Call: call}
}

// MockRepositoryTransactionsCall wrap *gomock.Call
type MockRepositoryTransactionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryTransactionsCall) Return(arg0 []entity.Transaction, arg1 int, arg2 error) *MockRepositoryTransactionsCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryTransactionsCall) Do(f func(context.Context, uuid.UUID, entity.TransactionFilter) ([]entity.Transaction, int, error)) *MockRepositoryTransactionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryTransactionsCall) DoAndReturn(f func(context.Context, uuid.UUID, entity.TransactionFilter) ([]entity.Transaction, int, error)) *MockRepositoryTransactionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateTransactionOrderID mocks base method.
func (m *MockRepository) UpdateTransactionOrderID(ctx context.Context, id, orderID uuid.UUID, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransactionOrderID", ctx, id, orderID, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransactionOrderID indicates an expected call of UpdateTransactionOrderID.
func (mr *MockRepositoryMockRecorder) UpdateTransactionOrderID(ctx, id, orderID, updatedAt any) *MockRepositoryUpdateTransactionOrderIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionOrderID", reflect.TypeOf((*MockRepository)(nil).UpdateTransactionOrderID), ctx, id, orderID, updatedAt)
	return &MockRepositoryUpdateTransactionOrderIDCall{Call: call}
}

// MockRepositoryUpdateTransactionOrderIDCall wrap *gomock.Call
type MockRepositoryUpdateTransactionOrderIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryUpdateTransactionOrderIDCall) Return(arg0 error) *MockRepositoryUpdateTransactionOrderIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryUpdateTransactionOrderIDCall) Do(f func(context.Context, uuid.UUID, uuid.UUID, time.Time) error) *MockRepositoryUpdateTransactionOrderIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryUpdateTransactionOrderIDCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID, time.Time) error) *MockRepositoryUpdateTransactionOrderIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateTransactionQRCID mocks base method.
func (m *MockRepository) UpdateTransactionQRCID(ctx context.Context, id uuid.UUID, qrcid string, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransactionQRCID", ctx, id, qrcid, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransactionQRCID indicates an expected call of UpdateTransactionQRCID.
func (mr *MockRepositoryMockRecorder) UpdateTransactionQRCID(ctx, id, qrcid, updatedAt any) *MockRepositoryUpdateTransactionQRCIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionQRCID", reflect.TypeOf((*MockRepository)(nil).UpdateTransactionQRCID), ctx, id, qrcid, updatedAt)
	return &MockRepositoryUpdateTransactionQRCIDCall{Call: call}
}

// MockRepositoryUpdateTransactionQRCIDCall wrap *gomock.Call
type MockRepositoryUpdateTransactionQRCIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryUpdateTransactionQRCIDCall) Return(arg0 error) *MockRepositoryUpdateTransactionQRCIDCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryUpdateTransactionQRCIDCall) Do(f func(context.Context, uuid.UUID, string, time.Time) error) *MockRepositoryUpdateTransactionQRCIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryUpdateTransactionQRCIDCall) DoAndReturn(f func(context.Context, uuid.UUID, string, time.Time) error) *MockRepositoryUpdateTransactionQRCIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateTransactionStatus mocks base method.
func (m *MockRepository) UpdateTransactionStatus(ctx context.Context, id uuid.UUID, status entity.TransactionStatus, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransactionStatus", ctx, id, status, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransactionStatus indicates an expected call of UpdateTransactionStatus.
func (mr *MockRepositoryMockRecorder) UpdateTransactionStatus(ctx, id, status, updatedAt any) *MockRepositoryUpdateTransactionStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionStatus", reflect.TypeOf((*MockRepository)(nil).UpdateTransactionStatus), ctx, id, status, updatedAt)
	return &MockRepositoryUpdateTransactionStatusCall{Call: call}
}

// MockRepositoryUpdateTransactionStatusCall wrap *gomock.Call
type MockRepositoryUpdateTransactionStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryUpdateTransactionStatusCall) Return(arg0 error) *MockRepositoryUpdateTransactionStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryUpdateTransactionStatusCall) Do(f func(context.Context, uuid.UUID, entity.TransactionStatus, time.Time) error) *MockRepositoryUpdateTransactionStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryUpdateTransactionStatusCall) DoAndReturn(f func(context.Context, uuid.UUID, entity.TransactionStatus, time.Time) error) *MockRepositoryUpdateTransactionStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockClientService is a mock of ClientService interface.
type MockClientService struct {
	ctrl     *gomock.Controller
	recorder *MockClientServiceMockRecorder
	isgomock struct{}
}

// MockClientServiceMockRecorder is the mock recorder for MockClientService.
type MockClientServiceMockRecorder struct {
	mock *MockClientService
}

// NewMockClientService creates a new mock instance.
func NewMockClientService(ctrl *gomock.Controller) *MockClientService {
	mock := &MockClientService{ctrl: ctrl}
	mock.recorder = &MockClientServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientService) EXPECT() *MockClientServiceMockRecorder {
	return m.recorder
}

// GetClientOwner mocks base method.
func (m *MockClientService) GetClientOwner(ctx context.Context, clientID uuid.UUID) (entity.ClientOwner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientOwner", ctx, clientID)
	ret0, _ := ret[0].(entity.ClientOwner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientOwner indicates an expected call of GetClientOwner.
func (mr *MockClientServiceMockRecorder) GetClientOwner(ctx, clientID any) *MockClientServiceGetClientOwnerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientOwner", reflect.TypeOf((*MockClientService)(nil).GetClientOwner), ctx, clientID)
	return &MockClientServiceGetClientOwnerCall{Call: call}
}

// MockClientServiceGetClientOwnerCall wrap *gomock.Call
type MockClientServiceGetClientOwnerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientServiceGetClientOwnerCall) Return(arg0 entity.ClientOwner, arg1 error) *MockClientServiceGetClientOwnerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientServiceGetClientOwnerCall) Do(f func(context.Context, uuid.UUID) (entity.ClientOwner, error)) *MockClientServiceGetClientOwnerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientServiceGetClientOwnerCall) DoAndReturn(f func(context.Context, uuid.UUID) (entity.ClientOwner, error)) *MockClientServiceGetClientOwnerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UserClient mocks base method.
func (m *MockClientService) UserClient(ctx context.Context, userID uuid.UUID) (entity.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserClient", ctx, userID)
	ret0, _ := ret[0].(entity.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserClient indicates an expected call of UserClient.
func (mr *MockClientServiceMockRecorder) UserClient(ctx, userID any) *MockClientServiceUserClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserClient", reflect.TypeOf((*MockClientService)(nil).UserClient), ctx, userID)
	return &MockClientServiceUserClientCall{Call: call}
}

// MockClientServiceUserClientCall wrap *gomock.Call
type MockClientServiceUserClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientServiceUserClientCall) Return(arg0 entity.Client, arg1 error) *MockClientServiceUserClientCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientServiceUserClientCall) Do(f func(context.Context, uuid.UUID) (entity.Client, error)) *MockClientServiceUserClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientServiceUserClientCall) DoAndReturn(f func(context.Context, uuid.UUID) (entity.Client, error)) *MockClientServiceUserClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Mock_1CService is a mock of _1CService interface.
type Mock_1CService struct {
	ctrl     *gomock.Controller
	recorder *Mock_1CServiceMockRecorder
	isgomock struct{}
}

// Mock_1CServiceMockRecorder is the mock recorder for Mock_1CService.
type Mock_1CServiceMockRecorder struct {
	mock *Mock_1CService
}

// NewMock_1CService creates a new mock instance.
func NewMock_1CService(ctrl *gomock.Controller) *Mock_1CService {
	mock := &Mock_1CService{ctrl: ctrl}
	mock.recorder = &Mock_1CServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mock_1CService) EXPECT() *Mock_1CServiceMockRecorder {
	return m.recorder
}

// CreateBill mocks base method.
func (m *Mock_1CService) CreateBill(ctx context.Context, i entity.Transaction) (entity.ClientRequisites, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBill", ctx, i)
	ret0, _ := ret[0].(entity.ClientRequisites)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBill indicates an expected call of CreateBill.
func (mr *Mock_1CServiceMockRecorder) CreateBill(ctx, i any) *Mock_1CServiceCreateBillCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBill", reflect.TypeOf((*Mock_1CService)(nil).CreateBill), ctx, i)
	return &Mock_1CServiceCreateBillCall{Call: call}
}

// Mock_1CServiceCreateBillCall wrap *gomock.Call
type Mock_1CServiceCreateBillCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *Mock_1CServiceCreateBillCall) Return(arg0 entity.ClientRequisites, arg1 error) *Mock_1CServiceCreateBillCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *Mock_1CServiceCreateBillCall) Do(f func(context.Context, entity.Transaction) (entity.ClientRequisites, error)) *Mock_1CServiceCreateBillCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *Mock_1CServiceCreateBillCall) DoAndReturn(f func(context.Context, entity.Transaction) (entity.ClientRequisites, error)) *Mock_1CServiceCreateBillCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockProducer is a mock of Producer interface.
type MockProducer struct {
	ctrl     *gomock.Controller
	recorder *MockProducerMockRecorder
	isgomock struct{}
}

// MockProducerMockRecorder is the mock recorder for MockProducer.
type MockProducerMockRecorder struct {
	mock *MockProducer
}

// NewMockProducer creates a new mock instance.
func NewMockProducer(ctrl *gomock.Controller) *MockProducer {
	mock := &MockProducer{ctrl: ctrl}
	mock.recorder = &MockProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducer) EXPECT() *MockProducerMockRecorder {
	return m.recorder
}

// SendUpdateBalance mocks base method.
func (m *MockProducer) SendUpdateBalance(ctx context.Context, txID, clientID uuid.UUID, amount decimal.Decimal) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendUpdateBalance", ctx, txID, clientID, amount)
}

// SendUpdateBalance indicates an expected call of SendUpdateBalance.
func (mr *MockProducerMockRecorder) SendUpdateBalance(ctx, txID, clientID, amount any) *MockProducerSendUpdateBalanceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendUpdateBalance", reflect.TypeOf((*MockProducer)(nil).SendUpdateBalance), ctx, txID, clientID, amount)
	return &MockProducerSendUpdateBalanceCall{Call: call}
}

// MockProducerSendUpdateBalanceCall wrap *gomock.Call
type MockProducerSendUpdateBalanceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProducerSendUpdateBalanceCall) Return() *MockProducerSendUpdateBalanceCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProducerSendUpdateBalanceCall) Do(f func(context.Context, uuid.UUID, uuid.UUID, decimal.Decimal)) *MockProducerSendUpdateBalanceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProducerSendUpdateBalanceCall) DoAndReturn(f func(context.Context, uuid.UUID, uuid.UUID, decimal.Decimal)) *MockProducerSendUpdateBalanceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockBankService is a mock of BankService interface.
type MockBankService struct {
	ctrl     *gomock.Controller
	recorder *MockBankServiceMockRecorder
	isgomock struct{}
}

// MockBankServiceMockRecorder is the mock recorder for MockBankService.
type MockBankServiceMockRecorder struct {
	mock *MockBankService
}

// NewMockBankService creates a new mock instance.
func NewMockBankService(ctrl *gomock.Controller) *MockBankService {
	mock := &MockBankService{ctrl: ctrl}
	mock.recorder = &MockBankServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBankService) EXPECT() *MockBankServiceMockRecorder {
	return m.recorder
}

// CardPaymentStatus mocks base method.
func (m *MockBankService) CardPaymentStatus(ctx context.Context, txID uuid.UUID) (entity.CardPaymentStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CardPaymentStatus", ctx, txID)
	ret0, _ := ret[0].(entity.CardPaymentStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CardPaymentStatus indicates an expected call of CardPaymentStatus.
func (mr *MockBankServiceMockRecorder) CardPaymentStatus(ctx, txID any) *MockBankServiceCardPaymentStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CardPaymentStatus", reflect.TypeOf((*MockBankService)(nil).CardPaymentStatus), ctx, txID)
	return &MockBankServiceCardPaymentStatusCall{Call: call}
}

// MockBankServiceCardPaymentStatusCall wrap *gomock.Call
type MockBankServiceCardPaymentStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBankServiceCardPaymentStatusCall) Return(arg0 entity.CardPaymentStatus, arg1 error) *MockBankServiceCardPaymentStatusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBankServiceCardPaymentStatusCall) Do(f func(context.Context, uuid.UUID) (entity.CardPaymentStatus, error)) *MockBankServiceCardPaymentStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBankServiceCardPaymentStatusCall) DoAndReturn(f func(context.Context, uuid.UUID) (entity.CardPaymentStatus, error)) *MockBankServiceCardPaymentStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateCardPayment mocks base method.
func (m *MockBankService) CreateCardPayment(ctx context.Context, txID uuid.UUID, amount decimal.Decimal, desc string) (entity.CardPayment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCardPayment", ctx, txID, amount, desc)
	ret0, _ := ret[0].(entity.CardPayment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCardPayment indicates an expected call of CreateCardPayment.
func (mr *MockBankServiceMockRecorder) CreateCardPayment(ctx, txID, amount, desc any) *MockBankServiceCreateCardPaymentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCardPayment", reflect.TypeOf((*MockBankService)(nil).CreateCardPayment), ctx, txID, amount, desc)
	return &MockBankServiceCreateCardPaymentCall{Call: call}
}

// MockBankServiceCreateCardPaymentCall wrap *gomock.Call
type MockBankServiceCreateCardPaymentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBankServiceCreateCardPaymentCall) Return(arg0 entity.CardPayment, arg1 error) *MockBankServiceCreateCardPaymentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBankServiceCreateCardPaymentCall) Do(f func(context.Context, uuid.UUID, decimal.Decimal, string) (entity.CardPayment, error)) *MockBankServiceCreateCardPaymentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBankServiceCreateCardPaymentCall) DoAndReturn(f func(context.Context, uuid.UUID, decimal.Decimal, string) (entity.CardPayment, error)) *MockBankServiceCreateCardPaymentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// OneTimeSPBLink mocks base method.
func (m *MockBankService) OneTimeSPBLink(ctx context.Context, tx entity.Transaction, requisites entity.ClientRequisites) (entity.SPBLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OneTimeSPBLink", ctx, tx, requisites)
	ret0, _ := ret[0].(entity.SPBLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OneTimeSPBLink indicates an expected call of OneTimeSPBLink.
func (mr *MockBankServiceMockRecorder) OneTimeSPBLink(ctx, tx, requisites any) *MockBankServiceOneTimeSPBLinkCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OneTimeSPBLink", reflect.TypeOf((*MockBankService)(nil).OneTimeSPBLink), ctx, tx, requisites)
	return &MockBankServiceOneTimeSPBLinkCall{Call: call}
}

// MockBankServiceOneTimeSPBLinkCall wrap *gomock.Call
type MockBankServiceOneTimeSPBLinkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBankServiceOneTimeSPBLinkCall) Return(arg0 entity.SPBLink, arg1 error) *MockBankServiceOneTimeSPBLinkCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBankServiceOneTimeSPBLinkCall) Do(f func(context.Context, entity.Transaction, entity.ClientRequisites) (entity.SPBLink, error)) *MockBankServiceOneTimeSPBLinkCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBankServiceOneTimeSPBLinkCall) DoAndReturn(f func(context.Context, entity.Transaction, entity.ClientRequisites) (entity.SPBLink, error)) *MockBankServiceOneTimeSPBLinkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SPBPaymentStatus mocks base method.
func (m *MockBankService) SPBPaymentStatus(ctx context.Context, txID uuid.UUID, qrcID string) (entity.SPBPaymentStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SPBPaymentStatus", ctx, txID, qrcID)
	ret0, _ := ret[0].(entity.SPBPaymentStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SPBPaymentStatus indicates an expected call of SPBPaymentStatus.
func (mr *MockBankServiceMockRecorder) SPBPaymentStatus(ctx, txID, qrcID any) *MockBankServiceSPBPaymentStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SPBPaymentStatus", reflect.TypeOf((*MockBankService)(nil).SPBPaymentStatus), ctx, txID, qrcID)
	return &MockBankServiceSPBPaymentStatusCall{Call: call}
}

// MockBankServiceSPBPaymentStatusCall wrap *gomock.Call
type MockBankServiceSPBPaymentStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBankServiceSPBPaymentStatusCall) Return(arg0 entity.SPBPaymentStatus, arg1 error) *MockBankServiceSPBPaymentStatusCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBankServiceSPBPaymentStatusCall) Do(f func(context.Context, uuid.UUID, string) (entity.SPBPaymentStatus, error)) *MockBankServiceSPBPaymentStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBankServiceSPBPaymentStatusCall) DoAndReturn(f func(context.Context, uuid.UUID, string) (entity.SPBPaymentStatus, error)) *MockBankServiceSPBPaymentStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
