run:
  go: "1.23"
  concurrency: 4
  issues-exit-code: 1
  tests: true
  modules-download-mode: mod
  allow-parallel-runners: true
  timeout: 5m
output:
  path-prefix: app

linters:
  enable-all: true
  disable:
    - exhaustruct
    - nonamedreturns
    - wrapcheck
    - gofumpt
    - gci
    - tagliatelle
    - musttag
    - varnamelen
    - nlreturn
    - err113
    - godot
    - tagalign
    - misspell
    - testpackage
    - testifylint
    - errname
    - cyclop
    - nestif
    - gochecknoglobals
    - interfacebloat

linters-settings:
  wsl:
    allow-cuddle-with-calls:
      - "sendErrorWithMsg"
      - "sendError"
      - "sendJSON"
      - "With"
      - "Info"
      - "Infof"
      - "Error"
      - "Errorf"
    allow-cuddle-with-rhs:
      - "sendErrorWithMsg"
      - "sendError"
      - "sendJSON"
      - "With"
      - "Info"
      - "Infof"
      - "Error"
      - "Errorf"
  gosec:
    excludes:
      - G401
      - G505
      - G306
  misspell:
    ignore-words:
      - sub_payed
  whitespace:
    multi-if: true
    multi-func: false
  lll:
    line-length: 140
  depguard:
    rules:
      main:
        list-mode: lax
        files:
          - $all
        allow:
          - $gostd
          - filippo.io/edwards25519
          - golang.org/x/crypto
          - github.com/jackc/pgx/v5
          - github.com/stretchr/testify
          - github.com/golang/mock/gomock
          - github.com/lib/pq
          - github.com/gofiber/fiber/v2
          - github.com/Masterminds/squirrel
          - golang.org/x/text/encoding/charmap
          - github.com/golang-jwt/jwt/v5
          - github.com/google/uuid
          - github.com/joho/godotenv
          - github.com/caarlos0/env/v6
          - github.com/pressly/goose/v3
          - github.com/shopspring/decimal
          - github.com/gofiber/contrib/jwt
          - github.com/prometheus/client_golang/prometheus/promhttp
        deny:
          - pkg: io/ioutil
            desc: "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"
  funlen:
    lines: 100
    ignore-comments: true
    statements: 50
  errcheck:
    exclude-functions:
      - (github.com/jackc/pgx/v5.Tx).Rollback
issues:
  exclude-rules:
    - linters:
        - lll
      source: ".*// "
