// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=../mocks/service.go -package=mocks -typed
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/gofrs/uuid/v5"
	entity "github.com/samandr77/microservices/documents/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ChangeClosingDocumentsRequestStatus mocks base method.
func (m *MockRepository) ChangeClosingDocumentsRequestStatus(ctx context.Context, guid uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeClosingDocumentsRequestStatus", ctx, guid)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeClosingDocumentsRequestStatus indicates an expected call of ChangeClosingDocumentsRequestStatus.
func (mr *MockRepositoryMockRecorder) ChangeClosingDocumentsRequestStatus(ctx, guid any) *MockRepositoryChangeClosingDocumentsRequestStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeClosingDocumentsRequestStatus", reflect.TypeOf((*MockRepository)(nil).ChangeClosingDocumentsRequestStatus), ctx, guid)
	return &MockRepositoryChangeClosingDocumentsRequestStatusCall{Call: call}
}

// MockRepositoryChangeClosingDocumentsRequestStatusCall wrap *gomock.Call
type MockRepositoryChangeClosingDocumentsRequestStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryChangeClosingDocumentsRequestStatusCall) Return(arg0 error) *MockRepositoryChangeClosingDocumentsRequestStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryChangeClosingDocumentsRequestStatusCall) Do(f func(context.Context, uuid.UUID) error) *MockRepositoryChangeClosingDocumentsRequestStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryChangeClosingDocumentsRequestStatusCall) DoAndReturn(f func(context.Context, uuid.UUID) error) *MockRepositoryChangeClosingDocumentsRequestStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CreateDocuments mocks base method.
func (m *MockRepository) CreateDocuments(ctx context.Context, documents ...entity.Document) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range documents {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDocuments", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDocuments indicates an expected call of CreateDocuments.
func (mr *MockRepositoryMockRecorder) CreateDocuments(ctx any, documents ...any) *MockRepositoryCreateDocumentsCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, documents...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDocuments", reflect.TypeOf((*MockRepository)(nil).CreateDocuments), varargs...)
	return &MockRepositoryCreateDocumentsCall{Call: call}
}

// MockRepositoryCreateDocumentsCall wrap *gomock.Call
type MockRepositoryCreateDocumentsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCreateDocumentsCall) Return(arg0 error) *MockRepositoryCreateDocumentsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCreateDocumentsCall) Do(f func(context.Context, ...entity.Document) error) *MockRepositoryCreateDocumentsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCreateDocumentsCall) DoAndReturn(f func(context.Context, ...entity.Document) error) *MockRepositoryCreateDocumentsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DocumentByClientID mocks base method.
func (m *MockRepository) DocumentByClientID(ctx context.Context, id uuid.UUID) (entity.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DocumentByClientID", ctx, id)
	ret0, _ := ret[0].(entity.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DocumentByClientID indicates an expected call of DocumentByClientID.
func (mr *MockRepositoryMockRecorder) DocumentByClientID(ctx, id any) *MockRepositoryDocumentByClientIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DocumentByClientID", reflect.TypeOf((*MockRepository)(nil).DocumentByClientID), ctx, id)
	return &MockRepositoryDocumentByClientIDCall{Call: call}
}

// MockRepositoryDocumentByClientIDCall wrap *gomock.Call
type MockRepositoryDocumentByClientIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryDocumentByClientIDCall) Return(arg0 entity.Document, arg1 error) *MockRepositoryDocumentByClientIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryDocumentByClientIDCall) Do(f func(context.Context, uuid.UUID) (entity.Document, error)) *MockRepositoryDocumentByClientIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryDocumentByClientIDCall) DoAndReturn(f func(context.Context, uuid.UUID) (entity.Document, error)) *MockRepositoryDocumentByClientIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DocumentByClientIDAndType mocks base method.
func (m *MockRepository) DocumentByClientIDAndType(ctx context.Context, clientID uuid.UUID, documentType entity.DocType) (entity.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DocumentByClientIDAndType", ctx, clientID, documentType)
	ret0, _ := ret[0].(entity.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DocumentByClientIDAndType indicates an expected call of DocumentByClientIDAndType.
func (mr *MockRepositoryMockRecorder) DocumentByClientIDAndType(ctx, clientID, documentType any) *MockRepositoryDocumentByClientIDAndTypeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DocumentByClientIDAndType", reflect.TypeOf((*MockRepository)(nil).DocumentByClientIDAndType), ctx, clientID, documentType)
	return &MockRepositoryDocumentByClientIDAndTypeCall{Call: call}
}

// MockRepositoryDocumentByClientIDAndTypeCall wrap *gomock.Call
type MockRepositoryDocumentByClientIDAndTypeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryDocumentByClientIDAndTypeCall) Return(arg0 entity.Document, arg1 error) *MockRepositoryDocumentByClientIDAndTypeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryDocumentByClientIDAndTypeCall) Do(f func(context.Context, uuid.UUID, entity.DocType) (entity.Document, error)) *MockRepositoryDocumentByClientIDAndTypeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryDocumentByClientIDAndTypeCall) DoAndReturn(f func(context.Context, uuid.UUID, entity.DocType) (entity.Document, error)) *MockRepositoryDocumentByClientIDAndTypeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DocumentByID mocks base method.
func (m *MockRepository) DocumentByID(ctx context.Context, documentID uuid.UUID) (entity.Document, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DocumentByID", ctx, documentID)
	ret0, _ := ret[0].(entity.Document)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DocumentByID indicates an expected call of DocumentByID.
func (mr *MockRepositoryMockRecorder) DocumentByID(ctx, documentID any) *MockRepositoryDocumentByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DocumentByID", reflect.TypeOf((*MockRepository)(nil).DocumentByID), ctx, documentID)
	return &MockRepositoryDocumentByIDCall{Call: call}
}

// MockRepositoryDocumentByIDCall wrap *gomock.Call
type MockRepositoryDocumentByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryDocumentByIDCall) Return(arg0 entity.Document, arg1 error) *MockRepositoryDocumentByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryDocumentByIDCall) Do(f func(context.Context, uuid.UUID) (entity.Document, error)) *MockRepositoryDocumentByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryDocumentByIDCall) DoAndReturn(f func(context.Context, uuid.UUID) (entity.Document, error)) *MockRepositoryDocumentByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DocumentsListByFilter mocks base method.
func (m *MockRepository) DocumentsListByFilter(ctx context.Context, filter entity.DocumentsFilter) ([]entity.Document, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DocumentsListByFilter", ctx, filter)
	ret0, _ := ret[0].([]entity.Document)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DocumentsListByFilter indicates an expected call of DocumentsListByFilter.
func (mr *MockRepositoryMockRecorder) DocumentsListByFilter(ctx, filter any) *MockRepositoryDocumentsListByFilterCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DocumentsListByFilter", reflect.TypeOf((*MockRepository)(nil).DocumentsListByFilter), ctx, filter)
	return &MockRepositoryDocumentsListByFilterCall{Call: call}
}

// MockRepositoryDocumentsListByFilterCall wrap *gomock.Call
type MockRepositoryDocumentsListByFilterCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryDocumentsListByFilterCall) Return(arg0 []entity.Document, arg1 int, arg2 error) *MockRepositoryDocumentsListByFilterCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryDocumentsListByFilterCall) Do(f func(context.Context, entity.DocumentsFilter) ([]entity.Document, int, error)) *MockRepositoryDocumentsListByFilterCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryDocumentsListByFilterCall) DoAndReturn(f func(context.Context, entity.DocumentsFilter) ([]entity.Document, int, error)) *MockRepositoryDocumentsListByFilterCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetClosingDocumentsRequestByGUID mocks base method.
func (m *MockRepository) GetClosingDocumentsRequestByGUID(ctx context.Context, guid uuid.UUID) (entity.ClosingDocumentsRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClosingDocumentsRequestByGUID", ctx, guid)
	ret0, _ := ret[0].(entity.ClosingDocumentsRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClosingDocumentsRequestByGUID indicates an expected call of GetClosingDocumentsRequestByGUID.
func (mr *MockRepositoryMockRecorder) GetClosingDocumentsRequestByGUID(ctx, guid any) *MockRepositoryGetClosingDocumentsRequestByGUIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClosingDocumentsRequestByGUID", reflect.TypeOf((*MockRepository)(nil).GetClosingDocumentsRequestByGUID), ctx, guid)
	return &MockRepositoryGetClosingDocumentsRequestByGUIDCall{Call: call}
}

// MockRepositoryGetClosingDocumentsRequestByGUIDCall wrap *gomock.Call
type MockRepositoryGetClosingDocumentsRequestByGUIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetClosingDocumentsRequestByGUIDCall) Return(arg0 entity.ClosingDocumentsRequest, arg1 error) *MockRepositoryGetClosingDocumentsRequestByGUIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetClosingDocumentsRequestByGUIDCall) Do(f func(context.Context, uuid.UUID) (entity.ClosingDocumentsRequest, error)) *MockRepositoryGetClosingDocumentsRequestByGUIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetClosingDocumentsRequestByGUIDCall) DoAndReturn(f func(context.Context, uuid.UUID) (entity.ClosingDocumentsRequest, error)) *MockRepositoryGetClosingDocumentsRequestByGUIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveClosingDocumentsRequest mocks base method.
func (m *MockRepository) SaveClosingDocumentsRequest(ctx context.Context, closingDocReq entity.ClosingDocumentsRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveClosingDocumentsRequest", ctx, closingDocReq)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveClosingDocumentsRequest indicates an expected call of SaveClosingDocumentsRequest.
func (mr *MockRepositoryMockRecorder) SaveClosingDocumentsRequest(ctx, closingDocReq any) *MockRepositorySaveClosingDocumentsRequestCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveClosingDocumentsRequest", reflect.TypeOf((*MockRepository)(nil).SaveClosingDocumentsRequest), ctx, closingDocReq)
	return &MockRepositorySaveClosingDocumentsRequestCall{Call: call}
}

// MockRepositorySaveClosingDocumentsRequestCall wrap *gomock.Call
type MockRepositorySaveClosingDocumentsRequestCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositorySaveClosingDocumentsRequestCall) Return(arg0 error) *MockRepositorySaveClosingDocumentsRequestCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositorySaveClosingDocumentsRequestCall) Do(f func(context.Context, entity.ClosingDocumentsRequest) error) *MockRepositorySaveClosingDocumentsRequestCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositorySaveClosingDocumentsRequestCall) DoAndReturn(f func(context.Context, entity.ClosingDocumentsRequest) error) *MockRepositorySaveClosingDocumentsRequestCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SignOferta mocks base method.
func (m *MockRepository) SignOferta(ctx context.Context, clientID uuid.UUID, signedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignOferta", ctx, clientID, signedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignOferta indicates an expected call of SignOferta.
func (mr *MockRepositoryMockRecorder) SignOferta(ctx, clientID, signedAt any) *MockRepositorySignOfertaCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignOferta", reflect.TypeOf((*MockRepository)(nil).SignOferta), ctx, clientID, signedAt)
	return &MockRepositorySignOfertaCall{Call: call}
}

// MockRepositorySignOfertaCall wrap *gomock.Call
type MockRepositorySignOfertaCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositorySignOfertaCall) Return(arg0 error) *MockRepositorySignOfertaCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositorySignOfertaCall) Do(f func(context.Context, uuid.UUID, time.Time) error) *MockRepositorySignOfertaCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositorySignOfertaCall) DoAndReturn(f func(context.Context, uuid.UUID, time.Time) error) *MockRepositorySignOfertaCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateDocumentsStatus mocks base method.
func (m *MockRepository) UpdateDocumentsStatus(ctx context.Context, oldStatus, newStatus entity.DocStatus, signedAt, olderThan time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDocumentsStatus", ctx, oldStatus, newStatus, signedAt, olderThan)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDocumentsStatus indicates an expected call of UpdateDocumentsStatus.
func (mr *MockRepositoryMockRecorder) UpdateDocumentsStatus(ctx, oldStatus, newStatus, signedAt, olderThan any) *MockRepositoryUpdateDocumentsStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDocumentsStatus", reflect.TypeOf((*MockRepository)(nil).UpdateDocumentsStatus), ctx, oldStatus, newStatus, signedAt, olderThan)
	return &MockRepositoryUpdateDocumentsStatusCall{Call: call}
}

// MockRepositoryUpdateDocumentsStatusCall wrap *gomock.Call
type MockRepositoryUpdateDocumentsStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryUpdateDocumentsStatusCall) Return(arg0 error) *MockRepositoryUpdateDocumentsStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryUpdateDocumentsStatusCall) Do(f func(context.Context, entity.DocStatus, entity.DocStatus, time.Time, time.Time) error) *MockRepositoryUpdateDocumentsStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryUpdateDocumentsStatusCall) DoAndReturn(f func(context.Context, entity.DocStatus, entity.DocStatus, time.Time, time.Time) error) *MockRepositoryUpdateDocumentsStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCampaigns is a mock of Campaigns interface.
type MockCampaigns struct {
	ctrl     *gomock.Controller
	recorder *MockCampaignsMockRecorder
	isgomock struct{}
}

// MockCampaignsMockRecorder is the mock recorder for MockCampaigns.
type MockCampaignsMockRecorder struct {
	mock *MockCampaigns
}

// NewMockCampaigns creates a new mock instance.
func NewMockCampaigns(ctrl *gomock.Controller) *MockCampaigns {
	mock := &MockCampaigns{ctrl: ctrl}
	mock.recorder = &MockCampaignsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCampaigns) EXPECT() *MockCampaignsMockRecorder {
	return m.recorder
}

// ActualCampaignInfo mocks base method.
func (m *MockCampaigns) ActualCampaignInfo(ctx context.Context, info entity.Report) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActualCampaignInfo", ctx, info)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActualCampaignInfo indicates an expected call of ActualCampaignInfo.
func (mr *MockCampaignsMockRecorder) ActualCampaignInfo(ctx, info any) *MockCampaignsActualCampaignInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActualCampaignInfo", reflect.TypeOf((*MockCampaigns)(nil).ActualCampaignInfo), ctx, info)
	return &MockCampaignsActualCampaignInfoCall{Call: call}
}

// MockCampaignsActualCampaignInfoCall wrap *gomock.Call
type MockCampaignsActualCampaignInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCampaignsActualCampaignInfoCall) Return(arg0 error) *MockCampaignsActualCampaignInfoCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCampaignsActualCampaignInfoCall) Do(f func(context.Context, entity.Report) error) *MockCampaignsActualCampaignInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCampaignsActualCampaignInfoCall) DoAndReturn(f func(context.Context, entity.Report) error) *MockCampaignsActualCampaignInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetCampaigns mocks base method.
func (m *MockCampaigns) GetCampaigns(ctx context.Context, clientID uuid.UUID, startDate, endDate time.Time) ([]entity.CampaignInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaigns", ctx, clientID, startDate, endDate)
	ret0, _ := ret[0].([]entity.CampaignInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaigns indicates an expected call of GetCampaigns.
func (mr *MockCampaignsMockRecorder) GetCampaigns(ctx, clientID, startDate, endDate any) *MockCampaignsGetCampaignsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaigns", reflect.TypeOf((*MockCampaigns)(nil).GetCampaigns), ctx, clientID, startDate, endDate)
	return &MockCampaignsGetCampaignsCall{Call: call}
}

// MockCampaignsGetCampaignsCall wrap *gomock.Call
type MockCampaignsGetCampaignsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCampaignsGetCampaignsCall) Return(arg0 []entity.CampaignInfo, arg1 error) *MockCampaignsGetCampaignsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCampaignsGetCampaignsCall) Do(f func(context.Context, uuid.UUID, time.Time, time.Time) ([]entity.CampaignInfo, error)) *MockCampaignsGetCampaignsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCampaignsGetCampaignsCall) DoAndReturn(f func(context.Context, uuid.UUID, time.Time, time.Time) ([]entity.CampaignInfo, error)) *MockCampaignsGetCampaignsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockClients is a mock of Clients interface.
type MockClients struct {
	ctrl     *gomock.Controller
	recorder *MockClientsMockRecorder
	isgomock struct{}
}

// MockClientsMockRecorder is the mock recorder for MockClients.
type MockClientsMockRecorder struct {
	mock *MockClients
}

// NewMockClients creates a new mock instance.
func NewMockClients(ctrl *gomock.Controller) *MockClients {
	mock := &MockClients{ctrl: ctrl}
	mock.recorder = &MockClientsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClients) EXPECT() *MockClientsMockRecorder {
	return m.recorder
}

// GetClientOwner mocks base method.
func (m *MockClients) GetClientOwner(ctx context.Context, clientID uuid.UUID) (entity.ClientOwner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientOwner", ctx, clientID)
	ret0, _ := ret[0].(entity.ClientOwner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientOwner indicates an expected call of GetClientOwner.
func (mr *MockClientsMockRecorder) GetClientOwner(ctx, clientID any) *MockClientsGetClientOwnerCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientOwner", reflect.TypeOf((*MockClients)(nil).GetClientOwner), ctx, clientID)
	return &MockClientsGetClientOwnerCall{Call: call}
}

// MockClientsGetClientOwnerCall wrap *gomock.Call
type MockClientsGetClientOwnerCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientsGetClientOwnerCall) Return(arg0 entity.ClientOwner, arg1 error) *MockClientsGetClientOwnerCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientsGetClientOwnerCall) Do(f func(context.Context, uuid.UUID) (entity.ClientOwner, error)) *MockClientsGetClientOwnerCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientsGetClientOwnerCall) DoAndReturn(f func(context.Context, uuid.UUID) (entity.ClientOwner, error)) *MockClientsGetClientOwnerCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetClientsInfo mocks base method.
func (m *MockClients) GetClientsInfo(ctx context.Context, id uuid.UUID) (entity.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientsInfo", ctx, id)
	ret0, _ := ret[0].(entity.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientsInfo indicates an expected call of GetClientsInfo.
func (mr *MockClientsMockRecorder) GetClientsInfo(ctx, id any) *MockClientsGetClientsInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientsInfo", reflect.TypeOf((*MockClients)(nil).GetClientsInfo), ctx, id)
	return &MockClientsGetClientsInfoCall{Call: call}
}

// MockClientsGetClientsInfoCall wrap *gomock.Call
type MockClientsGetClientsInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientsGetClientsInfoCall) Return(arg0 entity.Client, arg1 error) *MockClientsGetClientsInfoCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientsGetClientsInfoCall) Do(f func(context.Context, uuid.UUID) (entity.Client, error)) *MockClientsGetClientsInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientsGetClientsInfoCall) DoAndReturn(f func(context.Context, uuid.UUID) (entity.Client, error)) *MockClientsGetClientsInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUserClient mocks base method.
func (m *MockClients) GetUserClient(ctx context.Context, userID uuid.UUID) (entity.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserClient", ctx, userID)
	ret0, _ := ret[0].(entity.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserClient indicates an expected call of GetUserClient.
func (mr *MockClientsMockRecorder) GetUserClient(ctx, userID any) *MockClientsGetUserClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserClient", reflect.TypeOf((*MockClients)(nil).GetUserClient), ctx, userID)
	return &MockClientsGetUserClientCall{Call: call}
}

// MockClientsGetUserClientCall wrap *gomock.Call
type MockClientsGetUserClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientsGetUserClientCall) Return(arg0 entity.Client, arg1 error) *MockClientsGetUserClientCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientsGetUserClientCall) Do(f func(context.Context, uuid.UUID) (entity.Client, error)) *MockClientsGetUserClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientsGetUserClientCall) DoAndReturn(f func(context.Context, uuid.UUID) (entity.Client, error)) *MockClientsGetUserClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockOneC is a mock of OneC interface.
type MockOneC struct {
	ctrl     *gomock.Controller
	recorder *MockOneCMockRecorder
	isgomock struct{}
}

// MockOneCMockRecorder is the mock recorder for MockOneC.
type MockOneCMockRecorder struct {
	mock *MockOneC
}

// NewMockOneC creates a new mock instance.
func NewMockOneC(ctrl *gomock.Controller) *MockOneC {
	mock := &MockOneC{ctrl: ctrl}
	mock.recorder = &MockOneCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOneC) EXPECT() *MockOneCMockRecorder {
	return m.recorder
}

// GenerateDocuments mocks base method.
func (m *MockOneC) GenerateDocuments(ctx context.Context, report entity.Report, guid uuid.UUID, campaignsInfo []entity.CampaignInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDocuments", ctx, report, guid, campaignsInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// GenerateDocuments indicates an expected call of GenerateDocuments.
func (mr *MockOneCMockRecorder) GenerateDocuments(ctx, report, guid, campaignsInfo any) *MockOneCGenerateDocumentsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDocuments", reflect.TypeOf((*MockOneC)(nil).GenerateDocuments), ctx, report, guid, campaignsInfo)
	return &MockOneCGenerateDocumentsCall{Call: call}
}

// MockOneCGenerateDocumentsCall wrap *gomock.Call
type MockOneCGenerateDocumentsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOneCGenerateDocumentsCall) Return(arg0 error) *MockOneCGenerateDocumentsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOneCGenerateDocumentsCall) Do(f func(context.Context, entity.Report, uuid.UUID, []entity.CampaignInfo) error) *MockOneCGenerateDocumentsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOneCGenerateDocumentsCall) DoAndReturn(f func(context.Context, entity.Report, uuid.UUID, []entity.CampaignInfo) error) *MockOneCGenerateDocumentsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockS3 is a mock of S3 interface.
type MockS3 struct {
	ctrl     *gomock.Controller
	recorder *MockS3MockRecorder
	isgomock struct{}
}

// MockS3MockRecorder is the mock recorder for MockS3.
type MockS3MockRecorder struct {
	mock *MockS3
}

// NewMockS3 creates a new mock instance.
func NewMockS3(ctrl *gomock.Controller) *MockS3 {
	mock := &MockS3{ctrl: ctrl}
	mock.recorder = &MockS3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3) EXPECT() *MockS3MockRecorder {
	return m.recorder
}

// DownloadDocument mocks base method.
func (m *MockS3) DownloadDocument(ctx context.Context, url string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadDocument", ctx, url)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadDocument indicates an expected call of DownloadDocument.
func (mr *MockS3MockRecorder) DownloadDocument(ctx, url any) *MockS3DownloadDocumentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadDocument", reflect.TypeOf((*MockS3)(nil).DownloadDocument), ctx, url)
	return &MockS3DownloadDocumentCall{Call: call}
}

// MockS3DownloadDocumentCall wrap *gomock.Call
type MockS3DownloadDocumentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockS3DownloadDocumentCall) Return(arg0 []byte, arg1 error) *MockS3DownloadDocumentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockS3DownloadDocumentCall) Do(f func(context.Context, string) ([]byte, error)) *MockS3DownloadDocumentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockS3DownloadDocumentCall) DoAndReturn(f func(context.Context, string) ([]byte, error)) *MockS3DownloadDocumentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRoback is a mock of Roback interface.
type MockRoback struct {
	ctrl     *gomock.Controller
	recorder *MockRobackMockRecorder
	isgomock struct{}
}

// MockRobackMockRecorder is the mock recorder for MockRoback.
type MockRobackMockRecorder struct {
	mock *MockRoback
}

// NewMockRoback creates a new mock instance.
func NewMockRoback(ctrl *gomock.Controller) *MockRoback {
	mock := &MockRoback{ctrl: ctrl}
	mock.recorder = &MockRobackMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoback) EXPECT() *MockRobackMockRecorder {
	return m.recorder
}

// GetBroadcastReport mocks base method.
func (m *MockRoback) GetBroadcastReport(ctx context.Context, campaignIDs []int64, dateFrom, dateTo time.Time) (entity.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBroadcastReport", ctx, campaignIDs, dateFrom, dateTo)
	ret0, _ := ret[0].(entity.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBroadcastReport indicates an expected call of GetBroadcastReport.
func (mr *MockRobackMockRecorder) GetBroadcastReport(ctx, campaignIDs, dateFrom, dateTo any) *MockRobackGetBroadcastReportCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBroadcastReport", reflect.TypeOf((*MockRoback)(nil).GetBroadcastReport), ctx, campaignIDs, dateFrom, dateTo)
	return &MockRobackGetBroadcastReportCall{Call: call}
}

// MockRobackGetBroadcastReportCall wrap *gomock.Call
type MockRobackGetBroadcastReportCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRobackGetBroadcastReportCall) Return(arg0 entity.Report, arg1 error) *MockRobackGetBroadcastReportCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRobackGetBroadcastReportCall) Do(f func(context.Context, []int64, time.Time, time.Time) (entity.Report, error)) *MockRobackGetBroadcastReportCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRobackGetBroadcastReportCall) DoAndReturn(f func(context.Context, []int64, time.Time, time.Time) (entity.Report, error)) *MockRobackGetBroadcastReportCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
